### Penjelasan Matrix pada Python

Matrix adalah struktur data berbentuk dua dimensi yang terdiri dari baris dan kolom. Di Python, matrix biasanya direpresentasikan menggunakan **list of lists** atau menggunakan library seperti **NumPy** untuk manipulasi yang lebih mudah.

#### 1. **Matrix Pengukuran**
Matrix pengukuran adalah matrix yang berisi data hasil pengukuran, seperti suhu, jarak, atau waktu. Contohnya:

```python
# Contoh matrix pengukuran
pengukuran = [
    [23, 25, 22],  # Suhu dalam derajat Celcius
    [45, 50, 48],  # Kelembaban dalam persen
    [10, 12, 11]   # Kecepatan angin dalam km/jam
]
```

#### 2. **Matrix Satuan**
Matrix satuan adalah matrix yang berisi nilai-nilai satuan (identity matrix). Satuan ini sering digunakan dalam operasi matematika seperti transformasi linear. Matrix satuan memiliki nilai 1 di diagonal utama dan 0 di elemen lainnya.

Contoh matrix satuan 3x3:

```python
import numpy as np

# Membuat matrix satuan 3x3
matrix_satuan = np.eye(3)
print(matrix_satuan)
```

Output:
```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

#### Kesimpulan
- **Matrix pengukuran** digunakan untuk menyimpan data hasil pengukuran.
- **Matrix satuan** digunakan dalam operasi matematika, terutama dalam aljabar linear.

In [1]:
pengukuran = [
    [23, 25, 22],  # Suhu dalam derajat Celcius
    [45, 50, 48],  # Kelembaban dalam persen
    [10, 12, 11]   # Kecepatan angin dalam km/jam
]
print(pengukuran)

[[23, 25, 22], [45, 50, 48], [10, 12, 11]]


In [4]:
import numpy as np

# Membuat matrix satuan 3x3
matrix_satuan = np.eye(3)
print(matrix_satuan)

# Output:
"""[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]"""

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


'[[1. 0. 0.]\n [0. 1. 0.]\n [0. 0. 1.]]'

### Perbedaan Matriks Python dan Matriks NumPy dalam Hal Memori

1. **Matriks Python (List of Lists)**:
    - Matriks Python direpresentasikan sebagai **list of lists**. Setiap elemen dalam matriks adalah list yang terpisah.
    - **Penggunaan Memori**: Matriks Python tidak dioptimalkan untuk operasi numerik. Karena setiap elemen adalah objek Python, overhead memori lebih besar.
    - **Kecepatan**: Operasi pada matriks Python lebih lambat karena Python harus menangani tipe data dinamis dan struktur data yang tidak seragam.

2. **Matriks NumPy**:
    - Matriks NumPy direpresentasikan sebagai **array multidimensi**. Semua elemen dalam array memiliki tipe data yang sama (homogen).
    - **Penggunaan Memori**: NumPy menggunakan blok memori yang berdekatan untuk menyimpan data, sehingga lebih efisien dalam penggunaan memori.
    - **Kecepatan**: Operasi pada matriks NumPy jauh lebih cepat karena NumPy diimplementasikan dalam C dan menggunakan operasi vektor yang dioptimalkan.

### Implementasi dalam Real Projects

1. **Matriks Python**:
    - Cocok untuk **prototyping** atau **data kecil** yang tidak memerlukan operasi numerik kompleks.
    - Contoh: Menyimpan data sederhana seperti tabel kecil atau data pengukuran yang tidak memerlukan manipulasi matematis.

2. **Matriks NumPy**:
    - Digunakan dalam **data science**, **machine learning**, dan **scientific computing** karena efisiensi dan kecepatan.
    - Contoh:
      - **Image Processing**: Representasi gambar sebagai array NumPy untuk manipulasi piksel.
      - **Machine Learning**: Operasi pada matriks besar seperti perhitungan dot product atau invers matriks.
      - **Simulasi Fisika**: Menghitung transformasi linear atau simulasi berbasis matriks.

### Kesimpulan
- Gunakan **list of lists** untuk data kecil dan sederhana.
- Gunakan **NumPy** untuk operasi numerik yang membutuhkan efisiensi memori dan kecepatan, terutama pada data besar atau kompleks.

In [ ]:
import sys
# Perbandingan
matrix_python = [
    [1, 2, 3], [4, 5, 6], [7, 8, 9]
]

matriks_numpy = np.array([
    [1, 2, 3], [4, 5, 6], [7, 8, 9]
])

# Perbandingan hasil
print("Matrix Python:", matrix_python, "dengan size memori: ", sys.getsizeof(matrix_python)*len(matrix_python), "bytes")
print("Matrix Numpy:", matriks_numpy, "dengan size memori: ", matriks_numpy.size*matriks_numpy.itemsize, "bytes")




Matrix Python: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] dengan size memori:  240 bytes
Matrix Numpy: [[1 2 3]
 [4 5 6]
 [7 8 9]] dengan size memori:  72 bytes


Kode ini bertujuan untuk membandingkan penggunaan memori antara matriks yang dibuat menggunakan list standar Python dan matriks yang dibuat menggunakan library NumPy.

1. **Inisialisasi Matriks**:
    - `matrix_python`: Matriks 3x3 yang dibuat menggunakan *list of lists* (daftar di dalam daftar), cara standar di Python.
    - `matriks_numpy`: Matriks yang sama dibuat menggunakan `np.array()`, mengubah list Python menjadi array NumPy yang lebih efisien untuk operasi numerik.

2. **Perhitungan Ukuran Memori**:
    - **Untuk `matrix_python`**:
        - `sys.getsizeof(matrix_python)`: Mengukur ukuran objek list terluar dalam byte. Tidak menghitung ukuran list di dalamnya atau elemen integer secara rekursif.
        - `* len(matrix_python)`: Mengalikan ukuran list terluar dengan jumlah baris untuk memperkirakan total ukuran. Metode ini tidak sepenuhnya akurat karena setiap elemen dan sub-list adalah objek terpisah dengan overhead memori sendiri.
    - **Untuk `matriks_numpy`**:
        - `matriks_numpy.size`: Jumlah total elemen dalam array (3x3 = 9).
        - `matriks_numpy.itemsize`: Ukuran satu elemen dalam array dalam byte (misal, 8 byte untuk integer 64-bit).
        - `matriks_numpy.size * matriks_numpy.itemsize`: Memberikan ukuran memori yang tepat yang digunakan oleh data dalam array NumPy, karena NumPy menyimpan semua elemen dalam satu blok memori yang berdekatan.

**Kesimpulan**:  
Perbandingan ini menunjukkan bahwa NumPy jauh lebih efisien dalam penggunaan memori untuk data numerik dibandingkan list standar Python. Efisiensi ini menjadi alasan utama NumPy menjadi library fundamental untuk komputasi ilmiah dan analisis data di Python.


In [ ]:
#  Untuk mendekslarasi kan matriks pada matriks python ktia bisa langsung gunakan nested list seperti contoh diatas
matriks_nested = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

print("Matriks Nested:", matriks_nested, "dengan size memori: ", sys.getsizeof(matriks_nested)*len(matriks_nested), "bytes")


# pada matriks juga bisa gunakan default value lho, seperti
default_val = 0
matriks_def = [[default_val for j in range(3)] for i in range(3)]
print("Matriks Default:", matriks_def, "dengan size memori: ", sys.getsizeof(matriks_def)*len(matriks_def), "bytes")

matriks = [[3 for j in range(4)] for i in range(3)]

print(matriks)

Matriks Nested: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]] dengan size memori:  624 bytes
Matriks Default: [[0, 0, 0], [0, 0, 0], [0, 0, 0]] dengan size memori:  264 bytes
[[3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3]]


### Cara Mengakses Indexing pada Matriks di Python

Pada Python, matriks biasanya direpresentasikan sebagai **list of lists** (daftar di dalam daftar). Untuk mengakses elemen tertentu pada matriks, kita menggunakan teknik **indexing** dengan tanda kurung siku `[]`.

#### RUMUS INDEXING , var[nobaris][nocollumns]

#### 1. **Akses Elemen pada Matriks Python (List of Lists)**

Misalkan kita punya matriks berikut:
```python
matriks = [
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]
]
```

- **Akses baris ke-2 (indeks 1):**
  ```python
  matriks[1]
  # Output: [3, 3, 3, 3]
  ```

- **Akses elemen baris ke-2 kolom ke-3 (indeks 1, 2):**
  ```python
  matriks[1][2]
  # Output: 3
  ```

#### 2. **Akses Elemen pada Matriks NumPy**

Jika menggunakan NumPy array:
```python
import numpy as np
matriks_numpy = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
```

- **Akses baris ke-1 (indeks 0):**
  ```python
  matriks_numpy[0]
  # Output: array([1, 2, 3])
  ```

- **Akses elemen baris ke-3 kolom ke-2 (indeks 2, 1):**
  ```python
  matriks_numpy[2, 1]
  # Output: 8
  ```

#### 3. **Akses Submatriks (Slicing)**

- **Ambil dua baris pertama:**
  ```python
  matriks_numpy[:2]
  # Output: array([[1, 2, 3],
  #                [4, 5, 6]])
  ```

- **Ambil dua kolom pertama dari semua baris:**
  ```python
  matriks_numpy[:, :2]
  # Output: array([[1, 2],
  #                [4, 5],
  #                [7, 8]])
  ```

---

**Kesimpulan:**  
- Gunakan `matriks[baris][kolom]` untuk list of lists.
- Gunakan `array[baris, kolom]` untuk NumPy array.
- Indexing dimulai dari 0 (indeks pertama adalah 0).  
- Slicing memudahkan mengambil submatriks pada NumPy.

In [20]:
var_mat = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]
           
print(var_mat[2][1])

12


### Operasi Matriks pada Python

Operasi matriks adalah proses manipulasi data pada struktur matriks, baik menggunakan satu matriks (operasi satu matriks) maupun dua matriks (operasi dua matriks). Berikut penjelasan dan contoh kode untuk masing-masing operasi dasar:

---

#### **1. Operasi 1 Matriks**

##### a. Menghitung Total Semua Elemen Matriks

- **Python (List of Lists):**
    ```python
    total = sum(sum(row) for row in matriks)
    print("Total semua elemen matriks:", total)
    ```
- **NumPy:**
    ```python
    total = matriks_numpy.sum()
    print("Total semua elemen matriks (NumPy):", total)
    ```

##### b. Mengalikan Elemen Matriks dengan Konstanta

- **Python (List of Lists):**
    ```python
    hasil = [[elemen * konstanta for elemen in row] for row in matriks]
    print("Hasil perkalian matriks dengan konstanta:", hasil)
    ```
- **NumPy:**
    ```python
    hasil = matriks_numpy * konstanta
    print("Hasil perkalian matriks dengan konstanta (NumPy):\n", hasil)
    ```

##### c. Transpose Matriks

- **Python (List of Lists):**
    ```python
    transpose = [list(row) for row in zip(*matriks)]
    print("Transpose matriks:", transpose)
    ```
- **NumPy:**
    ```python
    transpose = matriks_numpy.T
    print("Transpose matriks (NumPy):\n", transpose)
    ```

##### d. Inverse Matriks (khusus matriks persegi & non-singular)

- **NumPy:**
    ```python
    inverse = np.linalg.inv(matriks_numpy)
    print("Inverse matriks (NumPy):\n", inverse)
    ```

##### e. Menentukan Determinan

- **NumPy:**
    ```python
    determinan = np.linalg.det(matriks_numpy)
    print("Determinan matriks (NumPy):", determinan)
    ```

---

#### **2. Operasi 2 Matriks**

##### a. Menambahkan Dua Matriks

- **NumPy:**
    ```python
    matriks_b = np.ones_like(matriks_numpy)
    penjumlahan = matriks_numpy + matriks_b
    print("Penjumlahan dua matriks (NumPy):\n", penjumlahan)
    ```

##### b. Mengalikan Dua Matriks (Dot Product)

- **NumPy:**
    ```python
    perkalian = np.dot(matriks_numpy, matriks_b)
    print("Perkalian dua matriks (NumPy):\n", perkalian)
    ```

##### c. Pembagian Dua Matriks

- **NumPy:**
    ```python
    pembagian = matriks_numpy / (matriks_b + 1)  # Hindari pembagian dengan nol
    print("Pembagian dua matriks (NumPy):\n", pembagian)
    ```

---

### **Kesimpulan**
- Operasi matriks dapat dilakukan dengan list of lists (untuk data sederhana) atau NumPy (untuk efisiensi dan kemudahan).
- NumPy sangat direkomendasikan untuk operasi numerik dan matriks yang kompleks.
- Setiap operasi memiliki fungsi dan sintaks yang berbeda, namun prinsip dasarnya sama: manipulasi data dalam bentuk dua dimensi.

In [22]:
# Penjelasan dan Contoh Operasi Matriks pada Python

# 1. Menghitung total semua elemen matriks (list of lists)
total_python = sum(sum(row) for row in matriks)
print("Total semua elemen matriks (Python):", total_python)

# 2. Mengalikan elemen matriks dengan konstanta (list of lists)
hasil_kali_python = [[elemen * konstanta for elemen in row] for row in matriks]
print("Hasil perkalian matriks dengan konstanta (Python):", hasil_kali_python)

# 3. Transpose matriks (list of lists)
transpose_python = [list(row) for row in zip(*matriks)]
print("Transpose matriks (Python):", transpose_python)

# 4. Operasi dengan NumPy (lebih mudah dan efisien)
# Menghitung total semua elemen matriks
total_numpy = matriks_numpy.sum()
print("Total semua elemen matriks (NumPy):", total_numpy)

# Mengalikan elemen matriks dengan konstanta
hasil_kali_numpy = matriks_numpy * konstanta
print("Hasil perkalian matriks dengan konstanta (NumPy):\n", hasil_kali_numpy)

# Transpose matriks
transpose_numpy = matriks_numpy.T
print("Transpose matriks (NumPy):\n", transpose_numpy)

# Inverse matriks (hanya untuk matriks persegi dan non-singular)
if matriks_numpy.shape[0] == matriks_numpy.shape[1]:
    try:
        inverse_numpy = np.linalg.inv(matriks_numpy)
        print("Inverse matriks (NumPy):\n", inverse_numpy)
    except np.linalg.LinAlgError:
        print("Matriks tidak memiliki inverse (singular).")
else:
    print("Inverse hanya untuk matriks persegi.")

# Determinan matriks (hanya untuk matriks persegi)
if matriks_numpy.shape[0] == matriks_numpy.shape[1]:
    determinan_numpy = np.linalg.det(matriks_numpy)
    print("Determinan matriks (NumPy):", determinan_numpy)
else:
    print("Determinan hanya untuk matriks persegi.")

# Operasi 2 matriks (penjumlahan dan perkalian)
# Contoh: Penjumlahan dua matriks NumPy
matriks_b = np.ones_like(matriks_numpy)
penjumlahan = matriks_numpy + matriks_b
print("Penjumlahan dua matriks (NumPy):\n", penjumlahan)

# Perkalian dua matriks (dot product)
perkalian = np.dot(matriks_numpy, matriks_b)
print("Perkalian dua matriks (NumPy):\n", perkalian)

Total semua elemen matriks (Python): 36
Hasil perkalian matriks dengan konstanta (Python): [[6, 6, 6, 6], [6, 6, 6, 6], [6, 6, 6, 6]]
Transpose matriks (Python): [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
Total semua elemen matriks (NumPy): 45
Hasil perkalian matriks dengan konstanta (NumPy):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Transpose matriks (NumPy):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Matriks tidak memiliki inverse (singular).
Determinan matriks (NumPy): 0.0
Penjumlahan dua matriks (NumPy):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Perkalian dua matriks (NumPy):
 [[ 6  6  6]
 [15 15 15]
 [24 24 24]]


In [23]:
var_mat = np.array([[5, 0],
                    [1, -2]])

result = var_mat * 2

print(result)

[[10  0]
 [ 2 -4]]
