# Pengenalan Library

Dalam pengembangan program atau aplikasi, kita tidak akan lepas dari peran package atau library. Sebagaimana yang sudah dijelaskan dalam materi-materi sebelumnya, package adalah sebuah direktori yang berisi satu atau lebih modul yang terkait dan saling berhubungan, sedangkan library adalah koleksi dari banyaknya modul dan paket yang saling terkait dan dapat digunakan berulang kali.

Pada materi ini, kita akan mempelajari berbagai library yang telah dikembangkan oleh banyak pengembang dan dapat digunakan kembali oleh kita. Jumlah library Python sangat banyak yang terbagi menjadi Python Standard Library dan Python External Library.

**Python Standard Library** adalah jenis library yang telah terinstal secara otomatis ketika kita melakukan instalasi Python. Anda tidak perlu melakukan instalasi kembali jika ingin menggunakannya. Beberapa contoh Python Standard Library adalah `os`, `datetime`, `re`, serta lainnya yang dapat Anda baca lebih lengkap pada laman berikut.

**Python External Library** adalah kumpulan kode yang telah dikembangkan oleh orang lain atau komunitas dan disediakan dalam bentuk paket atau modul yang dapat diimpor. Jenis library ini mengharuskan Anda untuk melakukan instalasi agar dapat digunakan. External library ini dikembangkan oleh individu atau organisasi di luar tim inti pengembang Python.

Untuk melakukan instalasi library eksternal, Anda dapat melakukan beberapa cara, seperti menggunakan **PIP** dan **conda**.

---

## PIP

PIP adalah package manager resmi dari Python yang dapat digunakan untuk mengunduh, menginstal, menghapus, dan mengelola package Python dari Python Package Index (PyPI) dan repositori lainnya. PyPI merupakan repositori online yang menyediakan ribuan package dari Python dan siap digunakan oleh para pengembang.

Selain mengelola paket, Anda juga bisa membuat lingkungan virtual dalam Python menggunakan PIP. Hanya saja, pip cenderung difokuskan untuk mengelola instalasi paket dibanding lingkungan virtual. Lingkungan virtual memungkinkan kita untuk membuat sebuah lingkungan terisolasi yang terpisah satu sama lain. Kita akan bahas lebih dalam terkait lingkungan virtual pada materi conda.

Kabar baiknya, pip biasanya telah terpasang secara otomatis jika Anda menggunakan Python 2 untuk versi 2.7.9 ke atas atau Python 3 untuk versi 3.4 ke atas. Maka dari itu, silakan periksa bahwa pip telah terpasang dengan menjalankan perintah berikut:

```
pip --version
```

Jika layar tidak memunculkan error, pip telah terinstal di lokal komputer Anda.

Jika lokal komputer Anda belum memiliki pip, Anda bisa mengikuti langkah-langkah berikut:

1. Unduh file berikut: https://bootstrap.pypa.io/get-pip.py.
2. Buka terminal dan buka folder tempat Anda menyimpan file yang telah diunduh. Kemudian jalankan perintah berikut:
    ```
    python get-pip.py
    ```

Sekarang, Anda telah menyiapkan pip sebagai package manager yang mendukung instalasi package dan library Python. Untuk melakukan instalasi, Anda bisa mengikuti perintah berikut:

```
pip install <nama-package>
```

Ganti `<nama-package>` dengan nama package atau library yang ingin Anda unduh. Untuk menghapus package, Anda bisa mengikuti perintah berikut:

```
pip uninstall <nama-package>
```

Contohnya, jika ingin membuat lingkungan virtual menggunakan pip, Anda harus menginstal package pipenv berikut:

```
pip install pipenv
```

---

## Conda

Selain pip yang termasuk package manager resmi dari Python, ada juga conda yang merupakan package manager dan environment manager untuk Python. Conda memungkinkan kita untuk membuat dan mengelola lingkungan (environment) terisolasi atau terpisah satu sama lain. Dengan terisolasinya setiap lingkungan tersebut, kita diuntungkan untuk mencegah konflik yang terjadi antar proyek.

Contohnya ketika Anda memiliki proyek machine learning dengan versi Python yang digunakan adalah Python 3.9. Di sisi lain, Anda memiliki proyek web development A dengan versi Python yang digunakan adalah Python 3.8. Ada pula proyek web development B dengan versi Python yang digunakan sama-sama menggunakan Python versi 3.8.

Dengan adanya lingkungan yang terisolasi, Anda bisa menyesuaikan semua library, modul, hingga versi Python sesuai dengan kebutuhan masing-masing proyek. Conda sendiri dapat diinstal melalui Anaconda dan Miniconda. Anaconda merupakan sistem distribusi perangkat lunak yang di dalamnya mencakup Conda. Ketika menginstal Anaconda, Anda pun dapat menggunakan beberapa library dan plugin tambahan melalui Anaconda tersebut. Miniconda adalah versi ringan dari Anaconda. Miniconda hanya berisi conda dan beberapa package dasar yang diperlukan untuk menjalankannya.

Conda sendiri hadir dalam dua bentuk utama: “conda” sebagai package dan environment manager serta “conda-forge”, yakni sebuah repositori berisi ribuan paket yang disediakan oleh komunitas Conda.

Kelebihan Conda adalah sifat tidak terbatasnya pada bahasa pemrograman Python. Conda juga mendukung paket-paket dalam bahasa pemrograman lain, seperti R.

### Instalasi Conda melalui Anaconda

1. Kunjungi laman berikut: https://www.anaconda.com/download.
2. Unduh Anaconda sesuai dengan sistem operasi Anda.
3. Jalankan file installer yang telah Anda unduh.
4. Ikuti petunjuk instalasi hingga selesai.

Setelah instalasi selesai, Anda dapat memeriksa bahwa conda telah terinstal dengan menjalankan perintah berikut pada terminal:

```
conda -V
```

Anda juga bisa membuka Anaconda Navigator untuk mengelola environment dan package secara visual.

Pelajari lebih lanjut tentang Conda di: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

---

Selanjutnya, mari kita pelajari beberapa library populer yang dapat digunakan oleh Anda.

```markdown
## Library Text Processing

Pertama adalah sekumpulan library yang bertujuan untuk melakukan pemrosesan teks dan menyederhanakan serta mempercepat tugas-tugas pemrosesan teks.

### String

String adalah salah satu modul bawaan Python yang tidak perlu dideklarasikan. Pada modul string ada fungsi-fungsi yang dapat dioperasikan pada variabel bertipe string seperti di bawah:

- `upper()`: Ubah setiap huruf dalam string menjadi huruf kapital.
- `lower()`: Ubah setiap huruf dalam string menjadi huruf kecil.
- `split()`: Pisahkan teks berdasarkan delimiter (karakter pemisah).
- `title()`: Jadikan setiap awal kata kapital.
- `zfill()`: Tambahkan nol di awal string sebanyak nilai yang ada pada parameter.

Contoh penerapan modul string:

![Contoh penggunaan modul string](dos:4d58174682a923145cf7d4f51004cfcd20230823202609.png)

---

### Regex

Regex atau regular expression adalah sebuah cara untuk mencari teks berdasarkan pola tertentu. Misalnya, ketika ingin mencari sebuah kata dalam kamus, regex bekerja dengan konsep yang sama dengan pencarian berdasarkan pola.

Pada regex, kita mencari sebuah kata atau kumpulan kata dengan memberikan pola yang diinginkan. Contoh umum regex adalah pada email, untuk mengecek bahwa karakter `@` ada pada email atau tidak.

Contoh di bawah menunjukkan penggunaan regex. Pada variabel `pola` di bawah, `^a` berarti kita ingin mencari teks dengan awalan 'a', dan `s$` berarti kita ingin mencari string berakhiran 's'.

```python
import re     # Import modul regex

pola = '^a...s$'
string_tes = 'abyss'
hasil = re.match(pola, string_tes)

if hasil:
    print("Pencarian berhasil.")
else:
    print("Pencarian gagal.")
```

**Output:**
```
Pencarian berhasil.
```

Perlu diperhatikan bahwa beberapa modul perlu diimpor terlebih dahulu untuk bisa digunakan. Pada contoh di atas, kita melakukan `import re` untuk mengimpor modul regex pada Python.
```

```markdown
## Library Pengolahan Data

Library pengolahan data bertujuan untuk membantu dalam manipulasi, analisis, dan pemrosesan data. Library ini menyediakan berbagai fungsi dan metode yang memudahkan pengguna untuk melakukan operasi pengolahan data dengan lebih efisien dan cepat.

Tujuan dari library ini adalah untuk menyederhanakan tugas-tugas kompleks yang berkaitan dengan pengolahan data sehingga Anda tidak perlu mengimplementasikan semuanya dari awal. Berikut adalah beberapa library populer yang digunakan untuk pengolahan data.

---

### Pandas

Pandas adalah library populer yang digunakan untuk pengelolaan dan analisis data. Library ini menyediakan struktur data dan alat untuk membantu pengguna dalam melakukan manipulasi, pembersihan, transformasi, dan analisis data dengan mudah dan efisien.

> **Instalasi Pandas:**
> ```
> pip install pandas
> ```
> atau dengan conda:
> ```
> conda install pandas
> ```

Contoh implementasi pandas:

![Contoh penggunaan pandas](dos:8b867c4f84dd4fed7a24f72ccfbb0bee20230823203848.png)

Pada contoh di atas, kita membuat DataFrame dari dictionary dan menampilkannya ke layar. DataFrame merupakan struktur data utama dalam pandas yang mirip seperti tabel atau spreadsheet, yaitu struktur dua dimensi yang menyimpan data dalam bentuk baris dan kolom.

---

### NumPy

Library NumPy adalah package fundamental yang sering digunakan untuk scientific computing pada Python. Library ini menyediakan objek array multidimensi, berbagai jenis objek lainnya, seperti masked array dan matrix, dan sebagainya.

> **Instalasi NumPy:**
> ```
> pip install numpy
> ```
> atau dengan conda:
> ```
> conda install numpy
> ```

Contoh penggunaan NumPy:
```python
import numpy

matriks = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print(matriks)
"""
Output:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
"""
```
Pada kode di atas, kita mengimpor library `numpy` terlebih dahulu untuk mengambil fungsi-fungsi atau kode yang berada pada library tersebut. Selanjutnya, mengubah nested list menjadi array dengan menggunakan fungsi `.array()`.

---

### Matplotlib

Matplotlib merupakan library untuk melakukan visualisasi data. Library ini termasuk jenis eksternal sehingga Anda perlu melakukan instalasi terlebih dahulu.

> **Instalasi Matplotlib:**
> ```
> python -m pip install -U matplotlib
> ```
> atau dengan conda:
> ```
> conda install matplotlib
> ```

Contoh penerapan matplotlib:
```python
import matplotlib.pyplot as plt

# Data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# Membuat plot garis
plt.plot(x, y)

# Menambahkan judul dan label sumbu
plt.title("Contoh Plot Garis")
plt.xlabel("Sumbu X")
plt.ylabel("Sumbu Y")

# Menampilkan plot
plt.show()
```
Pada kode di atas, kita membuat visualisasi berdasarkan data dari variabel `x` dan `y`. Pertama, kita mengimpor modul `matplotlib.pyplot` sebagai `plt`, lalu membuat variabel data, membuat plot garis, menambahkan judul dan label, dan menampilkan visualisasi.

Berikut adalah output ketika kode di atas dijalankan:

![Contoh output matplotlib](dos:85420d1dcc72d22b4ed77af55bc9c49b20230823204533.png)

---

### Seaborn

Seaborn adalah library visualisasi data yang dibangun di atas matplotlib. Library ini juga termasuk eksternal sehingga perlu diinstal terlebih dahulu.

> **Instalasi Seaborn:**
> ```
> pip install seaborn
> ```
> atau dengan conda:
> ```
> conda install seaborn
> ```

Contoh penerapan seaborn:
```python
import seaborn as sns
import matplotlib.pyplot as plt

# Contoh data
tips = sns.load_dataset('tips')  # Memuat dataset tips dari Seaborn

# Contoh plot histogram
sns.histplot(tips['total_bill'], kde=True)
plt.title('Histogram Total Bill')
plt.xlabel('Total Bill')
plt.ylabel('Frequency')
plt.show()
```
Pada contoh di atas, kita menggunakan seaborn untuk melakukan visualisasi berdasarkan dataset `tips`. Dataset ini adalah bawaan dari library seaborn yang dapat digunakan langsung. Untuk membuat plot histogram pada seaborn, Anda dapat menggunakan fungsi `sns.histplot()`.

Berikut adalah tampilannya ketika kode tersebut dijalankan.
```

In [3]:
import pickle
contoh_dictionary = {1:"6", 2:"2", 3:"f"}
pickle_keluar = open("dict.pickle","wb")
pickle.dump(contoh_dictionary, pickle_keluar)
pickle_keluar.close()

```markdown
## Library Web Scraping

Library web scraping adalah jenis library yang membantu pengguna mengumpulkan data dari halaman web. Proses ini disebut sebagai “web scraping” atau “web crawling”. Dengan library ini, Anda dapat mengekstrak informasi dari situs web dan menyimpannya dalam format yang dapat digunakan untuk analisis atau aplikasi lainnya.

Beberapa library populer untuk web scraping di Python antara lain:

### BeautifulSoup

BeautifulSoup adalah library untuk mengambil data dari halaman web dan mengekstrak informasi yang diperlukan. Untuk menggunakan BeautifulSoup, Anda perlu menginstalnya terlebih dahulu:

```
pip install beautifulsoup4
```

Contoh penggunaan BeautifulSoup:

```python
from urllib.request import urlopen
from bs4 import BeautifulSoup

# Pengambilan konten
url = "http://python.org/"
page = urlopen(url)
html = page.read().decode("utf-8")

# Membuat objek BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# Mencetak judul halaman
print(soup.title)
```

Pada contoh di atas, kita melakukan web scraping untuk mengambil judul dari laman web “http://python.org/”. Setelah mengambil konten dari URL, kita membuat objek BeautifulSoup dan dapat menampilkan konten berdasarkan tag HTML, misalnya judul halaman dengan `soup.title`.

---

### Urllib

Urllib adalah library bawaan Python yang digunakan untuk mengambil konten dari sebuah website. Penggunaan urllib sedikit berbeda dan lebih manual dibandingkan BeautifulSoup.

Contoh penggunaan urllib untuk mengambil judul halaman:

```python
from urllib.request import urlopen

# Pengambilan konten
url = "http://python.org/"
page = urlopen(url)
html = page.read().decode("utf-8")

# Mencari indeks awal dan akhir
start_index = html.find("<title>") + len("<title>")
end_index = html.find("</title>")

# Mengekstrak dan mencetak judul halaman
title = html[start_index:end_index]
print(title)
```

Pada kode di atas, kita mencari indeks awal dan akhir dari tag `<title>` dan `</title>`, lalu mengekstrak dan mencetak judul halaman tersebut.
```

In [6]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
 
# Pengambilan konten
url = "http://python.org/"
page = urlopen(url)
html = page.read().decode("utf-8")
 
# Membuat objek BeautifulSoup
soup = BeautifulSoup(html, "html.parser")
 
# Mencetak judul halaman
print(soup.p)

<p><strong>Notice:</strong> While JavaScript is not essential for this website, your interaction with the content will be limited. Please turn JavaScript on for the full experience. </p>


In [9]:
x = "Belajar" 
y = "Python" 
result = x > y 
print(result) 

False
