## Pengantar Unit Testing (Pengujian Unit) untuk Pemula

Saat belajar Python, kita sudah mengenal berbagai fitur seperti perulangan, fungsi, dan OOP. Namun, ketika aplikasi yang kita buat semakin besar dan kompleks, kita perlu memastikan bahwa setiap bagian aplikasi tetap berjalan dengan baik, terutama jika ada perubahan kode.

### Kenapa Perlu Pengujian?

Bayangkan kamu membuat aplikasi bersama teman. Mungkin kamu membuat satu fungsi, lalu temanmu membuat fungsi lain yang menggunakan fungsi milikmu. Jika kamu mengubah fungsi milikmu, bisa saja aplikasi temanmu jadi bermasalah. Mengecek satu per satu secara manual tentu melelahkan, apalagi jika fungsinya banyak.

### Jenis Pengujian

1. **Manual Testing**  
    Pengujian yang dilakukan langsung oleh manusia. Misalnya, kamu menjalankan program dan melihat hasilnya sesuai atau tidak.

2. **Automated Testing (Pengujian Otomatis)**  
    Pengujian yang dilakukan secara otomatis oleh program. Kita menulis kode khusus untuk menguji kode utama. Jika ada perubahan, kita tinggal jalankan tesnya, dan langsung tahu bagian mana yang bermasalah.

### Unit Testing vs Integration Testing

- **Integration Testing**  
  Menguji beberapa bagian aplikasi sekaligus sebagai satu kesatuan. Contohnya, menyalakan motor untuk mengecek apakah lampunya menyala. Jika lampu mati, bisa jadi masalahnya di bagian lain, bukan hanya lampunya.

- **Unit Testing**  
  Menguji bagian kecil secara spesifik, misalnya hanya lampunya saja. Dalam pemrograman, ini berarti menguji satu fungsi atau satu kelas secara terpisah.

### Library unittest di Python

Python sudah menyediakan library bernama `unittest` untuk melakukan unit testing. Dengan `unittest`, kita bisa:

- Menguji fungsi secara otomatis.
- Menyiapkan data sebelum tes dan membersihkannya setelah tes.
- Mengelompokkan beberapa tes menjadi satu.
- Memisahkan kode pengujian dari laporan hasil pengujian.

#### Istilah Penting di unittest

- **Test Fixture**: Persiapan sebelum tes (misal, membuat file sementara) dan pembersihan setelah tes.
- **Test Case**: Satu pengujian untuk satu fungsi atau fitur.
- **Test Suite**: Kumpulan beberapa test case yang dijalankan bersama.
- **Test Runner**: Program yang menjalankan semua tes dan menampilkan hasilnya.

---

Dengan unit testing, kita bisa memastikan setiap bagian aplikasi berjalan dengan baik, bahkan setelah ada perubahan kode. Ini sangat membantu, terutama saat aplikasi sudah besar atau dikerjakan bersama tim.

In [ ]:
import unittest


class TestStringMethods(unittest.TestCase):
    # Ini adalah test case pertama (1)
    def test_strip(self):
        self.assertEqual('www.dicoding.com'.strip('c.mow'), 'dicoding')
    
    # Test case kedua (2)
    def test_isalnum(self):
        self.assertTrue('c0d1ng'.isalnum())
        self.assertFalse('c0d!ng'.isalnum())
    
    # Test case ketiga (3)
    def test_index(self):
        s = 'dicoding'
        self.assertEqual(s.index('coding'), 2)
        # cek s.index gagal ketika tidak ditemukan
        with self.assertRaises(ValueError):
            s.index('decode')
    
if __name__ == '__main__':
    # Test Runner
    unittest.main()

#  Output
"""
    PS D:\Fahri\project olivia\dicoding DBS Foundation> python unitTestExample.py
    ...
    ----------------------------------------------------------------------
    Ran 3 tests in 0.001s

    OK
    PS D:\Fahri\project olivia\dicoding DBS Foundation> 
"""

Mari kita bahas satu per satu dari kode di atas.

Kelas `TestStringMethods` adalah turunan dari `unittest.TestCase`, sehingga dapat langsung digunakan untuk membuat unit test tanpa banyak implementasi tambahan.

Setiap metode yang namanya diawali dengan `test` akan dikenali sebagai test case oleh test runner. Pada setiap metode, pengujian dilakukan menggunakan berbagai macam assert, seperti:

- `assertEqual` untuk memastikan dua nilai sama.
- `assertTrue` untuk memastikan ekspresi bernilai benar.
- `assertFalse` untuk memastikan ekspresi bernilai salah.
- `assertRaises` untuk memastikan error tertentu muncul.

Contoh:
- Pada `test_strip`, digunakan `assertEqual` untuk memastikan hasil strip sesuai harapan.
- Pada `test_isalnum`, digunakan `assertTrue` dan `assertFalse` untuk memeriksa hasil fungsi `isalnum()`.
- Pada `test_index`, digunakan `assertEqual` dan `assertRaises` untuk memeriksa hasil pencarian substring dan error yang muncul jika substring tidak ditemukan.

Pemanggilan `unittest.main()` di akhir kode akan menjalankan seluruh test case yang sudah dibuat.

Jika semua test berhasil, akan muncul tanda titik (`...`) pada output, diikuti ringkasan waktu dan status `OK`. Jika ada test yang gagal, akan muncul detail error pada output.

Anda bisa mencoba mengubah salah satu assert agar test gagal, misalnya dengan mengganti semua menjadi `assertTrue` pada `test_isalnum`, untuk melihat perbedaan hasil keluaran.

```markdown
## Rangkuman Unit Testing

Kita telah mempelajari pentingnya unit testing dalam pengembangan aplikasi, terutama ketika aplikasi semakin kompleks dan memiliki banyak dependensi antar fungsi. Pengujian diperlukan untuk memastikan setiap bagian aplikasi tetap berjalan dengan baik meskipun ada perubahan kode.

### Jenis Pengujian

- **Manual Testing**: Pengujian dilakukan secara langsung oleh manusia.
- **Automated Testing**: Pengujian dilakukan secara otomatis menggunakan kode.
- **Integration Testing**: Menguji sistem sebagai satu kesatuan.
- **Unit Testing**: Menguji bagian kecil (unit) aplikasi secara spesifik.

### Library unittest di Python

Python menyediakan library `unittest` untuk melakukan unit testing secara otomatis. Fitur utama yang didukung antara lain:
- Pengujian otomatis.
- Setup dan teardown yang dapat digunakan ulang.
- Pengelompokan pengujian dalam test suite.
- Pemisahan framework pengujian dari pelaporan hasil.

#### Konsep Penting pada unittest

- **Test Fixture**: Persiapan dan pembersihan sebelum/akhir pengujian.
- **Test Case**: Unit pengujian untuk memeriksa respons terhadap input tertentu.
- **Test Suite**: Kumpulan test case atau test suite lain.
- **Test Runner**: Komponen yang menjalankan pengujian dan menampilkan hasil.

### Contoh Penerapan unittest

```python
import unittest

def koneksi_ke_db():
    print("[terhubung ke db]")

def putus_koneksi_db(db):
    print("[tidak terhubung ke db {}]".format(db))

class User:
    username = ""
    aktif = False

    def __init__(self, db, username):
        self.username = username

    def set_aktif(self):
        self.aktif = True

class TestUser(unittest.TestCase):
    # Test Case 1
    def test_user_default_not_active(self):
        db = koneksi_ke_db()
        user = User(db, "dicoding")
        self.assertFalse(user.aktif)
        putus_koneksi_db(db)
```

Dengan unit testing, kita dapat memastikan setiap fungsi berjalan sesuai harapan dan memudahkan deteksi error lebih awal dalam proses pengembangan.
```

In [8]:
import numpy

matriks = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print(matriks)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import matplotlib.pyplot as plt
 
# Data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
 
# Membuat plot garis
plt.plot(x, y)
 
# Menambahkan judul dan label sumbu
plt.title("Contoh Plot Garis")
plt.xlabel("Sumbu X")
plt.ylabel("Sumbu Y")
 
# Menampilkan plot
plt.show()

## Visualisasi Data dengan Seaborn

Seaborn adalah library eksternal Python yang digunakan untuk visualisasi data dan dibangun di atas matplotlib. Seaborn menyediakan tampilan grafik yang lebih menarik dan mudah digunakan, terutama untuk analisis data statistik.

### Instalasi Seaborn

Untuk menggunakan seaborn, Anda perlu menginstalnya terlebih dahulu:

```bash
pip install seaborn
```
atau jika menggunakan conda:
```bash
conda install seaborn
```

### Contoh Penggunaan Seaborn

Berikut contoh membuat histogram menggunakan seaborn dengan dataset bawaan `tips`:

```python
import seaborn as sns
import matplotlib.pyplot as plt

# Memuat dataset tips dari seaborn
tips = sns.load_dataset('tips')

# Membuat histogram kolom total_bill
sns.histplot(tips['total_bill'], kde=True)
plt.title('Histogram Total Bill')
plt.xlabel('Total Bill')
plt.ylabel('Frequency')
plt.show()
```

Pada contoh di atas:
- Dataset `tips` dimuat dari seaborn.
- Fungsi `sns.histplot()` digunakan untuk membuat histogram dari kolom `total_bill`.
- Fungsi dari matplotlib digunakan untuk menambahkan judul dan label pada grafik.

Seaborn sangat membantu untuk membuat visualisasi data yang informatif dan menarik dengan sintaks yang sederhana.